import type { Request, Response } from 'express';
import Product from '../models/product.js';
import { SiteSettingsModel } from '../models/siteSettings.js';
import { deleteFromCloudinaryByUrl } from '../utils/cloudinaryDelete.js';

export const getProducts = async (req: Request, res: Response): Promise<void> => {
  try {
    const { category, isActive } = req.query;
    const query: Record<string, unknown> = {};

    if (category) query.category = category;
    if (isActive !== undefined) query.isActive = isActive === 'true';

    // Global 2D filtering for public requests
    const isAdmin = (req as any).admin;
    if (!isAdmin) {
      const settings = await SiteSettingsModel.findOne();
      if (settings && settings.is2DEnabled === false) {
        query.categoryType = { $ne: '2d' };
      }
    }

    const products = await Product.find(query).sort({ createdAt: -1 });
    res.status(200).json({ success: true, count: products.length, data: products });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error fetching products',
      error: (error as Error).message,
    });
  }
};

export const getProduct = async (req: Request, res: Response): Promise<void> => {
  try {
    const id = req.params.id as string;
    let query: Record<string, string> = {};

    if (/^[0-9a-fA-F]{24}$/.test(id)) {
      query = { _id: id } as Record<string, string>;
    } else {
      query = { slug: id };
    }

    const product = await Product.findOne(query);

    if (!product) {
      res.status(404).json({ success: false, message: 'Product not found' });
      return;
    }

    // Global 2D filtering for public requests
    const isAdmin = (req as any).admin;
    if (!isAdmin && (product as any).categoryType === '2d') {
      const settings = await SiteSettingsModel.findOne();
      if (settings && settings.is2DEnabled === false) {
        res.status(404).json({ success: false, message: 'Product not found (Disabled)' });
        return;
      }
    }

    res.status(200).json({ success: true, data: product });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error fetching product',
      error: (error as Error).message,
    });
  }
};

export const createProduct = async (req: Request, res: Response): Promise<void> => {
  try {
    // slug auto-generated by Product model's pre('validate') hook if not provided
    const product = await Product.create(req.body);
    res.status(201).json({ success: true, data: product });
  } catch (error) {
    const err = error as Error & { code?: number };
    const isDuplicate = err.code === 11000 || /E11000|duplicate key/i.test(err.message);
    const friendlyMessage = isDuplicate
      ? 'A product with this name or slug already exists. Please use a different name.'
      : err.message;
    res.status(400).json({
      success: false,
      message: isDuplicate ? 'Product already exists' : 'Error creating product',
      error: friendlyMessage,
    });
  }
};

function slugify(s: string): string {
  if (!s || typeof s !== 'string') return 'item';
  return s.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '') || 'item';
}

export const updateProduct = async (req: Request, res: Response): Promise<void> => {
  try {
    const oldProduct = await Product.findById(req.params.id);
    if (oldProduct) {
      const {
        extractCloudinaryUrlsFromProduct,
        extractPublicIdFromUrl,
        deleteFromCloudinaryByUrl,
        extractFolderPrefixFromUrl
      } = await import('../utils/cloudinaryDelete.js');

      const oldUrls = extractCloudinaryUrlsFromProduct(oldProduct);
      const newUrlsRaw = extractCloudinaryUrlsFromProduct(req.body);

      const newUrls = new Set(newUrlsRaw);
      const newPublicIds = new Set(newUrlsRaw.map(u => extractPublicIdFromUrl(u)).filter(Boolean));

      // CRITICAL FIX: Ensure we don't accidentally delete an image that shares a Public ID. 
      // If a user overwrites an image, Cloudinary gives the new string a new timestamp (v100 -> v200) 
      // but keeps the identical Public ID. If we delete the old v100 Public ID, we instantly delete the new v200 image!
      const removedUrls = oldUrls.filter(oldUrl => {
        if (newUrls.has(oldUrl)) return false; // Exact match, retain it

        const oldPid = extractPublicIdFromUrl(oldUrl);
        if (oldPid && newPublicIds.has(oldPid)) return false; // Shared Public ID (Overwritten via React UI), retain it

        return true; // Completely orphaned, safe to DESTROY
      });

      // Concurrently delete all completely detached Cloudinary assets
      const deletePromises = removedUrls.map(url =>
        deleteFromCloudinaryByUrl(url).catch(err =>
          console.error('[productController] Background deletion failed for orphaned URL:', url, err)
        )
      );

      // Fire and forget: once files are deleted, attempt to sweep their empty parent directories
      Promise.all(deletePromises).then(async () => {
        const { extractFolderPrefixFromUrl } = await import('../utils/cloudinaryDelete.js');
        const { cloudinary } = await import('../config/cloudinary.js');

        // Collect unique parent folders of the deleted assets
        const parentFolders = new Set<string>();
        for (const url of removedUrls) {
          const folder = extractFolderPrefixFromUrl(url);
          if (folder) parentFolders.add(folder.slice(0, -1)); // Remove trailing slash for Cloudinary API
        }

        // Attempt to delete the empty folders. 
        // Cloudinary will safely ignore this if the folder still contains other active files.
        for (const folder of parentFolders) {
          try {
            await cloudinary.api.delete_folder(folder);
            // Also attempt to delete the parent group folder just in case it's now empty
            const grandParent = folder.split('/').slice(0, -1).join('/');
            if (grandParent) await cloudinary.api.delete_folder(grandParent);
          } catch (e) {
            // Expected to fail silently if the folder isn't completely empty yet
          }
        }
      }).catch(console.error);
    }

    const product = await Product.findByIdAndUpdate(req.params.id, req.body, {
      returnDocument: 'after',
      runValidators: true,
    });

    if (!product) {
      res.status(404).json({ success: false, message: 'Product not found' });
      return;
    }

    res.status(200).json({ success: true, data: product });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: 'Error updating product',
      error: (error as Error).message,
    });
  }
};

export const deleteProduct = async (req: Request, res: Response): Promise<void> => {
  try {
    const { deleteProductWithAssets } = await import('../utils/deleteHandlers.js');
    const { deleted, assetsDeleted } = await deleteProductWithAssets(req.params.id as string);

    if (!deleted) {
      res.status(404).json({ success: false, message: 'Product not found' });
      return;
    }

    res.status(200).json({ success: true, message: 'Product deleted successfully', assetsDeleted: assetsDeleted ?? 0 });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error deleting product',
      error: (error as Error).message,
    });
  }
};
